### ISSUE TITLE
hasAssets can return true if value is negative

### ISSUE THREAD

**Issue by Danlowe95** [lindy-labs/sc_solidity-contracts#149]
https://github.com/lindy-labs/sc_solidity-contracts/blob/33c2902f220559c5cfee46b57834b9665857b050/contracts/strategy/yearn/YearnStrategy.sol#L118

This may be a non-issue, but in reviewing the code this seems worth confirming.

This was recently changed from a `> 0` check to `!= 0` 

1. Is it possible for this return value to be negative?
2. If the value is negative, what would the outcome be?

**Comment by gabrielpoca** [comment]
Hello @Danlowe95 👋 that's not the reason because `_getShares` returns an unsigned int.
This was a gas optimization. See [here](https://github.com/byterocket/c4-common-issues/blob/main/0-Gas-Optimizations.md/#g003---use--0-instead-of--0-for-unsigned-integer-comparison). In retrospective, in the context of this function, it won't make any difference

**Comment by Danlowe95** [comment]
Thanks for the link to explain. Figured that would be the answer and I appreciate the reading material!
