### ISSUE TITLE
Vault - Deposit Test

### ISSUE THREAD

**Issue by joaop21** [lindy-labs/sc_solidity-contracts#92]
https://github.com/lindy-labs/sc_solidity-contracts/blob/1e014f10f9e68f7e8902cf96c1fd146dcd30a4c5/test/Vault.spec.ts#L907-L951

Are we actually testing that different deposits emit a different groupID?
Being the groupID the second argument emitted in an event, and checking only the 2 events emitted by the second transaction, I don't think that this test reveals a clear intention on what we are testing.
Or probably I'm missing something 😄

**Comment by coolhill** [comment]
essentially `"emits events"` does the first deposit and then `"emits events with a different groupId per deposit"` does the second deposit and checks that the new group id is 1 and not 0. but the two tests are dependent(not isolated in a good way) which makes it hard to read. yes @naps62 ?

**Comment by naps62** [comment]
@joaop21 by "tests are dependant", I think what @coolhill means is that, because the previous test checks for the groupId being 0, and this one checks for groupId on the 2nd deposit being 1, it kind of ends up proving the expectation, but only because the previous test ensures a different number
or in other words: if the previous test didn't exist, then you weren't actually proving they're different. this way you are proving it, but not in a very good way, apparently

I agree we can change this (essentally adding the extra checks to the 2nd test)

**Comment by joaop21** [comment]
Ohh I see, I assumed that by dependent you meant a real functional dependency. My bad @coolhill 😅 
This way it makes sense, even though I don't think it's the best or the clearest approach. 👍 
Thank you! 🙌
